---
repositories:
  - name: hashicorp
    url: https://helm.releases.hashicorp.com

  - name: external-secrets
    url: https://charts.external-secrets.io

  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: harbor
    url: https://helm.goharbor.io

releases:
  - name: vault
    namespace: vault
    chart: hashicorp/vault
    version: 0.32.0
    values:
      - values-vault.yaml

  - name: external-secrets
    namespace: external-secrets
    chart: external-secrets/external-secrets
    version: 2.6.0
    values:
      - values-external-secrets.yaml

  - name: postgres
    namespace: postgres
    chart: bitnami/postgresql
    version: 18.8.8
    values:
      - values-postgres.yaml

  - name: redis
    namespace: redis
    chart: bitnami/redis
    version: 28.0.2
    values:
      - values-redis.yaml
