---
releases:
  - name: vault
    namespace: vault
    chart: ./charts/vault-0.32.0.tgz
    values:
      - ./values-vault-k3s.yaml

  - name: external-secrets
    namespace: external-secrets
    chart: ./charts/external-secrets-2.6.0.tgz
    values:
      - ./values-external-secrets.yaml

  - name: postgres
    namespace: postgres
    chart: ./charts/postgresql-18.8.8.tgz
    values:
      - ./values-postgres-k3s.yaml

  - name: redis
    namespace: redis
    chart: ./charts/redis-28.0.2.tgz
    values:
      - ./values-redis.yaml

  - name: headlamp
    namespace: headlamp
    chart: ./charts/headlamp-0.45.0.tgz
    values:
      - ./values-headlamp.yaml

  - name: gitlab-runner
    namespace: gitlab-runner
    chart: ./charts/gitlab-runner-0.93.0.tgz
    values:
      - ./values-gitlab-runner.yaml
