---
repositories:
  - name: nginx-stable
    url: https://helm.nginx.com/stable

  # - name: bitnami
  #   url: https://charts.bitnami.com/bitnami

  # - name: harbor
  #   url: https://helm.goharbor.io

  # - name: prometheus-community
  #   url: https://prometheus-community.github.io/helm-charts

releases:
  - name: nginx-ingress
    namespace: nginx-ingress
    chart: nginx-stable/nginx-ingress
    version: 2.5.3
    values:
      - values-nginx-ingress.yaml

  # - name: postgres
  #   namespace: postgres
  #   chart: bitnami/postgresql
  #   version: 18.5.15
  #   values:
  #     - values-postgres.yaml

  # - name: redis
  #   namespace: redis
  #   chart: bitnami/redis
  #   version: 25.3.11
  #   values:
  #     - values-redis.yaml

  # - name: harbor
  #   namespace: harbor
  #   chart: harbor/harbor
  #   version: 1.18.3
  #   values:
  #     - values-harbor.yaml

  # - name: kube-prometheus-stack
  #   namespace: monitoring
  #   chart: prometheus-community/kube-prometheus-stack
  #   version: 85.2.1
  #   values:
  #     - values-kube-prometheus-stack.yaml
