---
repositories:
  - name: metallb
    url: https://metallb.github.io/metallb

  - name: traefik
    url: https://traefik.github.io/charts

  - name: jetstack
    url: https://charts.jetstack.io

  # - name: hashicorp
  #   url: https://helm.releases.hashicorp.com

  # - name: external-secrets
  #   url: https://charts.external-secrets.io

  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: harbor
    url: https://helm.goharbor.io

  # - name: prometheus-community
  #   url: https://prometheus-community.github.io/helm-charts

releases:
  - name: metallb
    namespace: metallb
    chart: metallb/metallb
    version: 0.16.1
    values:
      - values-metallb.yaml

  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: 41.3.0
    values:
      - values-traefik.yaml

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.21.1
    values:
      - values-cert-manager.yaml

  # - name: vault
  #   namespace: vault
  #   chart: hashicorp/vault
  #   version: 0.32.0
  #   values:
  #     - values-vault.yaml

  # - name: external-secrets
  #   namespace: external-secrets
  #   chart: external-secrets/external-secrets
  #   version: 2.6.0
  #   values:
  #     - values-external-secrets.yaml

  - name: postgres
    namespace: postgres
    chart: bitnami/postgresql
    version: 18.8.8
    values:
      - values-postgres.yaml

  - name: redis
    namespace: redis
    chart: bitnami/redis
    version: 28.0.2
    values:
      - values-redis.yaml

  - name: harbor
    namespace: harbor
    chart: harbor/harbor
    version: 1.19.2
    values:
      - values-harbor.yaml

  # - name: kube-prometheus-stack
  #   namespace: monitoring
  #   chart: prometheus-community/kube-prometheus-stack
  #   version: 85.2.1
  #   values:
  #     - values-kube-prometheus-stack.yaml
