---
releases:
  - name: vault
    namespace: vault
    chart: ./charts/vault-0.32.0.tgz
    values:
      - ./values-vault.yaml

  - name: external-secrets
    namespace: external-secrets
    chart: ./charts/external-secrets-2.6.0.tgz
    values:
      - ./values-external-secrets.yaml

  - name: postgres
    namespace: postgres
    chart: ./charts/postgresql-18.8.8.tgz
    values:
      - ./values-postgres.yaml

  - name: redis
    namespace: redis
    chart: ./charts/redis-28.0.2.tgz
    values:
      - ./values-redis.yaml
