global:
  compatibility:
    openshift:
      adaptSecurityContext: "disabled"

crds:
  createClusterExternalSecret: false
  createSecretStore: false
  createClusterGenerator: false
  createClusterPushSecret: false
  createPushSecret: false

openshiftFinalizers: false

processClusterExternalSecret: false

processClusterPushSecret: false

processSecretStore: false

processClusterGenerator: false

processPushSecret: false

resources: {}   # temporary value

serviceMonitor:
  enabled: false   # temporary value
