global:
  compatibility:
    openshift:
      adaptSecurityContext: "disabled"

installCRDs: true

crds:
  createClusterExternalSecret: false
  createClusterSecretStore: false
  createSecretStore: true
  createClusterGenerator: false
  createClusterPushSecret: false
  createPushSecret: false

openshiftFinalizers: false

processClusterExternalSecret: false
processClusterStore: false
processSecretStore: true
processClusterGenerator: false
processClusterPushSecret: false
processPushSecret: false

resources: {}   # temporary value

serviceMonitor:
  enabled: false   # temporary value
