global:
  compatibility:
    openshift:
      adaptSecurityContext: "disabled"

installCRDs: true

crds:
  createClusterExternalSecret: false
  createClusterSecretStore: true
  createSecretStore: false
  createClusterGenerator: false
  createClusterPushSecret: false
  createPushSecret: false

openshiftFinalizers: false

processClusterExternalSecret: false
processClusterStore: true
processSecretStore: false
processClusterGenerator: false
processClusterPushSecret: false
processPushSecret: false

serviceAccount:
  create: true
  name: external-secrets
  automount: true

rbac:
  create: true
  serviceAccountTokenCreate: true

resources: {}   # temporary value

serviceMonitor:
  enabled: false   # temporary value
