controller:
  replicaCount: 3
  ingressClass:
    name: nginx
    create: true
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    httpPort:
      port: 80
      targetPort: 80
    httpsPort:
      port: 443
      targetPort: 443
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  config:
    entries:
      use-proxy-protocol: "false"
      use-forwarded-headers: "true"
      compute-full-forwarded-for: "true"
      enable-real-ip: "true"
      log-format-escape-json: "true"
  healthStatus: true
rbac:
  create: true
  clusterrole:
    create: true
prometheus:
  create: true
  service:
    create: true
  serviceMonitor:
    create: false # temporary value
