expose:
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: harbor-tls
  ingress:
    hosts:
      core: cr.utz.ru
    className: traefik
externalURL: https://cr.utz.ru
harborAdminPassword: admin
persistence:
  enabled: true
  storageClass: standard
  persistentVolumeClaim:
    registry:
      size: 5Gi
    jobservice:
      size: 1Gi
database:
  type: external
  external:
    host: postgres-postgresql.postgres.svc.cluster.local
    port: 5432
    username: harbor
    password: sasha-12345
    dbname: registry
    sslmode: disable
redis:
  type: external
  external:
    addr: redis-master.redis.svc.cluster.local:6379
    password: sasha-12345
trivy:
  enabled: false
registry:
  enabled: true
  initContainers:
    - name: init-registry
      image: busybox
      securityContext:
        runAsUser: 0
      command: ["sh", "-c", "mkdir -p /storage && chown -R 10000:10000 /storage"]
      volumeMounts:
        - name: registry-data
          mountPath: /storage
