expose:
  tls:
    enabled: false
  ingress:
    hosts:
      core: harbor.local
    className: nginx
externalURL: http://harbor.local:30080   # temporary value
harborAdminPassword: admin
persistence:
  enabled: true
  storageClass: standard
  persistentVolumeClaim:
    registry:
      size: 5Gi
    jobservice:
      size: 1Gi
    trivy:
      size: 1Gi
database:
  type: external
  external:
    host: postgres-postgresql.postgres.svc.cluster.local
    port: 5432
    username: sasha
    password: secret-123
    dbname: registry
    sslmode: disable
redis:
  type: external
  external:
    addr: redis-master.redis.svc.cluster.local:6379
    password: admin
trivy:
  enabled: false
registry:
  enabled: true
  initContainers:
    - name: init-registry
      image: busybox
      securityContext:
        runAsUser: 0
      command: ["sh", "-c", "mkdir -p /storage && chown -R 10000:10000 /storage"]
      volumeMounts:
        - name: registry-data
          mountPath: /storage
