apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls
  namespace: harbor
spec:
  secretName: harbor-tls
  dnsNames:
    - cr.utz.ru
  issuerRef:
    name: minikube-ca
    kind: ClusterIssuer
    group: cert-manager.io
