{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "balance-orchestrator.fullname" . }}-gitlab
  labels:
    {{- include "balance-orchestrator.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.externalSecret.spec | nindent 2 }}
{{- end }}
