apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-auth
  namespace: postgres
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: postgres-auth
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: infra/postgres
        property: password
