---
releases:
  - name: balance-plus-bootstrap
    namespace: balance-plus
    chart: ./balance-plus/bootstrap

  - name: balance-plus
    namespace: balance-plus
    chart: ./balance-plus
    needs:
      - balance-plus/balance-plus-bootstrap
